### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [MindorksOpenSource/SnapHelperExample#1]
I get this error:
![image](https://user-images.githubusercontent.com/5357526/33063507-55ed6be8-ceab-11e7-9f5a-c87a466c52fc.png)

**Comment by amitshekhariitbhu** [comment]
The error is not related to this project. It's something related to kotlin.

**Comment by AndroidDeveloperLB** [comment]
How can I fix this?
I've already tried to uninstall the IDE, including the SDK, and re-install everything again...

**Comment by AndroidDeveloperLB** [comment]
never mind. Removed the Kotlin plugin and it works fine now. No idea why it got triggered
